Step 2 failure

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -4,30 +4,38 @@ on: [push]
 jobs:
   job-1:
     runs-on: ubuntu-latest
+    timeout-minutes: 1
     steps:
       - name: Step 1
-        run: sleep 20
+        run: sleep 90
+        # timeout-minutes: 1
 
-      - name: Fail
+      - name: Step 2
+        id: step-2
         run: exit 1
-      
+
+      - name: Runs on step 2 Failure
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
+
       - name: Runs on Failure
         if: failure()
-        run: echo 'Runs only on failure'
+        run: echo 'Failure'
 
       - name: Runs on Success
-        # This is not needed (DEFAULT BEHAVIOR)
+        # This is not needed (DEFAULT BEAHAVIOUR)
         if: success()
-        run: echo 'Runs on success'
+        run: echo 'Runs on Success'
 
       - name: Always Runs
+        # if: success() || failure()
         if: always()
-        run: 'Always Runs'
+        run: echo 'Always Runs'
 
       - name: Runs When Cancelled
         if: cancelled()
-        run: 'Runs on Cancelled'
-
+        run: echo 'Runs on Cancelled'
+        
   job-2:
     runs-on: ubuntu-latest
     needs: job-1
